---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: task-management-system
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/khaledhawil/End-to-End-DevOps-AWS-Nodejs-Python-MySQL.git
  # For private repos, add secretRef:
  # secretRef:
  #   name: github-credentials
